### ISSUE TITLE
FEATURE: `style` key should optional in shortcode

### ISSUE THREAD

**Issue by coatless** [quarto-ext/fontawesome#24]
Consider the following 

```
{{< fa book style="color: #003262" title="Reading Assignment Icon" >}} 
```

This is evaluated to:

```
<i class="fa-solid fa-book" title="Reading Assignment Icon" aria-label="book">
```

Notice the `style` keyword that allows for `color` to be set is MIA. 

The expected output would be:

```
<i class="fa-solid fa-book" style="color: #003262" title="Reading Assignment Icon" aria-label="book">
```

Though, glancing at the minimal example, I think the `style` keyword was intentionally omitted. Thus, this is more of a feature request than a bug report.

https://github.com/quarto-ext/fontawesome/blob/main/example.qmd

**Comment by cscheid** [comment]
`style` is, as you've seen, not supported. But it's also not necessary: wrap the shortcode with a span that includes the desired style:

`[{{< fa book title="Reading Assignment Icon" >}}]{style="color:#003262"}`

We don't want to include all possible ways in which an element can be annotated, by design.

**Comment by coatless** [comment]
@cscheid wonderful! Thank you.
